### ISSUE TITLE
investigation: Use Gson 

### ISSUE THREAD

**Issue by TomaszCza** [TomaszCza/fantasy#2]
FantasySavingScheduledService uses JsonArray and JsonObject to deseriliase json, and then gson to convert it to a Player object,
maybe it's possible to use Gson for both.

Acceptance criteria :
Investigate whether Gson can be used instead of current implementation.

**Comment by danielmfitz** [comment]
The line:
`JSONArray allPlayers = allInfo.getJSONArray("elements");`

is really handy for filtering out just the players from the entire JSON object we get from the premier league API, and it doesn't look like there's any similar clean functionality within Gson that'll do that without the help of other objects/libraries like JSONArray.

There are some people solving a similar issue here: https://stackoverflow.com/questions/22358243/get-json-key-name-using-gson and the manual methods look pretty messy and unreadable compared to this, which is only 2 lines and very readable :D
