### ISSUE TITLE
investigation: replacment for TeamEnum 

### ISSUE THREAD

**Issue by TomaszCza** [TomaszCza/fantasy#4]
TeamEnum is not done in a very good way, it might be possible to do it differently.

Acceptance criteria:
TeamEnum code refactored if possible.

**Comment by danielmfitz** [comment]
I see the API has a teams key with each code and respective team name - we could use the scheduler and something like Caffeine to cache a map from that info

**Comment by TomaszCza** [comment]
Do we expect players to change teams/ teams to update? How does Caffeine work exactly ? It might be a better solution :D

**Comment by danielmfitz** [comment]
It saves the trouble if the API ever changes (i.e. between years teams and team IDs get shuffled etc), prevents human error if a map/enum gets mistyped and it's probably just a little more convenient in the long run, having a list of ~20 teams to maintain is harder than just letting Java do it :p (plus it could be fun to implement)

**Comment by TomaszCza** [comment]
Go for it! Create a new issue !
